import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import {
  Avatar,
  Box,
  Menu,
  MenuButton,
  MenuItem,
  MenuList,
} from "@chakra-ui/react";
import currentUser from "@/helpers/currentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await currentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Box display={"flex"} flexDirection={"column"} h={"100vh"}>
            <Box
              display={"flex"}
              flexDir={"row"}
              minH={"60px"}
              borderBottom={1}
              borderStyle={"solid"}
              borderColor={"gray.200"}
              alignItems={"center"}
              paddingX={4}
            >
              <Box>Short</Box>
              <Box flexGrow={1}></Box>

              {user && (
                <Menu>
                  <MenuButton>
                    <Avatar
                      size={"sm"}
                      src={"https://avatars.dicebear.com/api/male/username.svg"}
                    />
                  </MenuButton>

                  <MenuList>
                    <MenuItem>Settings</MenuItem>
                    <MenuItem as={"a"} href="/logout" color={"red.400"}>
                      Logout
                    </MenuItem>
                  </MenuList>
                </Menu>
              )}
            </Box>
            {children}
          </Box>
        </Providers>
      </body>
    </html>
  );
}
